"""Generate the commented ``sr4rec.yaml`` and ``docs/config_reference.md`` from the schema.

Both outputs are produced from :mod:`sr4rec.config`, so the comments users see
can never drift away from what the validator accepts.
"""

from __future__ import annotations

import textwrap
from typing import Any

import yaml
from pydantic import BaseModel
from pydantic.fields import FieldInfo
from pydantic_core import PydanticUndefined

from . import __version__
from .config import CHECK_MARKER, Config, SRModelConfig

WIDTH = 88

HEADER = f"""\
# =============================================================================
# SR4Rec configuration file (SR4Rec v{__version__})
#
# Generated by `sr4rec init`. Lines marked {CHECK_MARKER} were inferred by SR4Rec:
# confirm or edit the value, then delete the "{CHECK_MARKER}" marker.
# `sr4rec run` refuses to start while any {CHECK_MARKER} marker remains.
#
# Each key is documented with:
#   type     : value type
#   required : yes | no | conditional
#   default  : value used when the key is omitted
#   allowed  : the complete list of accepted values, or the valid range
#
# Unknown keys are rejected, so typos never pass silently.
# Full reference: docs/config_reference.md
# =============================================================================
"""

SR_EXAMPLES = """\
  # - name: realesrgan                              # method 1: weights file
  #   weights: weights/RealESRGAN_x4plus.pth
  # - name: my_sr                                   # method 2: your PyTorch class
  #   module: sr_models/tiny_espcn.py:TinyESPCN
  #   weights: weights/tiny_espcn_x4.pth
  # - name: my_method                               # method 3: pre-computed images
  #   images: sr_images/my_method/
"""

SR_INTRO = """\
The bicubic baseline is always added automatically; do not list it.
Each entry needs `name` and ONE source (step-by-step guide: docs/adding_sr_models.md;
runnable examples: examples/configs/02, 05, 06):
  method 1 (weights) : `weights` only           -> loaded with spandrel
  method 2 (module)  : `module` (+ `weights`)   -> your own PyTorch class
  method 3 (images)  : `images` only            -> pre-computed SR images
Check every entry with `sr4rec run <config> --dry-run` before a real run."""


def format_value(value: Any) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, float):
        text = repr(value)
        return text
    if isinstance(value, (list, tuple)):
        return "[" + ", ".join(format_value(v) for v in value) + "]"
    if isinstance(value, dict):
        return "{" + ", ".join(f"{k}: {format_value(v)}" for k, v in value.items()) + "}"
    if isinstance(value, str):
        # YAML quoting only when needed (e.g. "my data #1", "2024", "yes", "a: b")
        return yaml.safe_dump(value, default_flow_style=True, width=10**6).split("\n...")[0].strip()
    return str(value)


def _default_of(info: FieldInfo) -> Any:
    if info.default is not PydanticUndefined:
        return info.default
    if info.default_factory is not None:
        val = info.default_factory()
        return val.model_dump() if isinstance(val, BaseModel) else val
    return PydanticUndefined


def _extra(info: FieldInfo) -> dict:
    return dict(info.json_schema_extra or {})


def _comment_block(info: FieldInfo, indent: str) -> list[str]:
    ex = _extra(info)
    if "doc" not in ex:
        return []
    lines = []
    for chunk in textwrap.wrap(ex["doc"], WIDTH - len(indent) - 2):
        lines.append(f"{indent}# {chunk}")
    default = _default_of(info)
    if ex.get("required") == "yes" or default is PydanticUndefined:
        default_text = "none"
    else:
        default_text = ex.get("default_repr", format_value(default))
    lines.append(f"{indent}#   type: {ex['type']} | required: {ex.get('required', 'no')} | default: {default_text}")
    allowed = ex["allowed"]
    if isinstance(allowed, list):
        lines.append(f"{indent}#   allowed:")
        for item in allowed:
            head = item.split(" : ", 1)[0] if " : " in item else ""
            pad = " " * (len(head) + 3) if head else "  "
            wrapped = textwrap.wrap(item, WIDTH - len(indent) - 7, subsequent_indent=pad)
            for chunk in wrapped:
                lines.append(f"{indent}#     {chunk}")
    else:
        lines.append(f"{indent}#   allowed: {allowed}")
    return lines


def _render_model(model: type[BaseModel], values: dict, notes: dict, indent: str, prefix: str) -> list[str]:
    out: list[str] = []
    for key, info in model.model_fields.items():
        path = f"{prefix}{key}"
        ann = info.annotation
        sub = _submodel(ann)
        out.extend(_comment_block(info, indent))
        if sub is not None:
            out.append(f"{indent}{key}:")
            out.extend(_render_model(sub, values.get(key, {}), notes, indent + "  ", path + "."))
        else:
            val = values[key] if key in values else _default_of(info)
            line = f"{indent}{key}: {format_value(val)}"
            if path in notes:
                line += f"  # {notes[path]}"
            out.append(line)
        out.append("")
    if out and out[-1] == "":
        out.pop()
    return out


def _submodel(ann: Any) -> type[BaseModel] | None:
    return ann if isinstance(ann, type) and issubclass(ann, BaseModel) else None


def _banner(title: str) -> list[str]:
    bar = "# " + "-" * 77
    return ["", "", bar, f"# {title}", bar]


def render_config(values: dict | None = None, notes: dict | None = None) -> str:
    """Render a fully commented configuration.

    ``values`` overrides defaults (nested dicts for nested sections; ``sr`` is a
    list of entry dicts). ``notes`` maps dotted key paths to inline comments,
    for example ``{"mode": "[CHECK] suggested: ..."}``.
    """
    values = values or {}
    notes = notes or {}
    lines = [HEADER.rstrip("\n")]
    for key, info in Config.model_fields.items():
        ex = _extra(info)
        if "section" in ex:
            lines.extend(_banner(ex["section"]))
            if key == "sr":
                for chunk in SR_INTRO.splitlines():
                    lines.append(f"# {chunk}" if chunk else "#")
                lines.append("#")
                for fkey, finfo in SRModelConfig.model_fields.items():
                    fex = _extra(finfo)
                    lines.append(f"#   {fkey}:")
                    for chunk in textwrap.wrap(fex["doc"], WIDTH - 8):
                        lines.append(f"#       {chunk}")
                    default = _default_of(finfo)
                    dtext = "none" if default is PydanticUndefined else format_value(default)
                    lines.append(f"#       type: {fex['type']} | required: {fex['required']} | default: {dtext}")
                    lines.append(f"#       allowed: {fex['allowed']}")
                lines.append("# " + "-" * 77)
        if key == "sr":
            entries = values.get("sr", [])
            lines.append("sr:" if entries else "sr: []")
            for e in entries:
                first = True
                for k, v in e.items():
                    if v is None:
                        continue
                    lines.append(f"  {'- ' if first else '  '}{k}: {format_value(v)}")
                    first = False
            lines.append(SR_EXAMPLES.rstrip("\n"))
            continue
        sub = _submodel(info.annotation)
        if sub is not None:
            lines.extend(_comment_block(info, ""))
            lines.append(f"{key}:")
            lines.extend(_render_model(sub, values.get(key, {}), notes, "  ", key + "."))
        else:
            if "section" not in ex:
                lines.append("")
            lines.extend(_comment_block(info, ""))
            val = values[key] if key in values else _default_of(info)
            line = f"{key}: {format_value(val)}"
            if key in notes:
                line += f"  # {notes[key]}"
            lines.append(line)
    return "\n".join(lines).rstrip("\n") + "\n"


def iter_fields(model: type[BaseModel] = Config, prefix: str = ""):
    """Yield (dotted path, FieldInfo) for every documented field, recursively."""
    for key, info in model.model_fields.items():
        path = f"{prefix}{key}"
        sub = _submodel(info.annotation)
        if key == "sr" and model is Config:
            for fkey, finfo in SRModelConfig.model_fields.items():
                yield f"sr[].{fkey}", finfo
            continue
        if "doc" in _extra(info):
            yield path, info
        if sub is not None:
            yield from iter_fields(sub, path + ".")


def render_reference() -> str:
    """Render docs/config_reference.md."""
    lines = [
        "# Configuration reference",
        "",
        "This file is generated from the configuration schema (`src/sr4rec/config.py`) by",
        "`python scripts/make_config_docs.py`. Do not edit it by hand.",
        "",
        "Every key of `sr4rec.yaml` is listed with its type, whether it is required, its default",
        "value and the complete set of accepted values. Unknown keys are rejected.",
        "",
        "| Key | Type | Required | Default | Allowed | Description |",
        "|---|---|---|---|---|---|",
    ]
    for path, info in iter_fields():
        ex = _extra(info)
        default = _default_of(info)
        if ex.get("required") == "yes" or default is PydanticUndefined:
            dtext = "none"
        else:
            dtext = ex.get("default_repr", format_value(default))
        allowed = ex["allowed"]
        if isinstance(allowed, list):
            allowed = "<br>".join(a.replace("|", "\\|") for a in allowed)
        else:
            allowed = str(allowed).replace("|", "\\|")
        lines.append(
            f"| `{path}` | {ex['type'].replace('|', chr(92) + '|')} | {ex.get('required', 'no')} | `{dtext}` | {allowed} | {ex['doc'].replace('|', chr(92) + '|')} |"
        )
    return "\n".join(lines) + "\n"
