"""Main results table in LaTeX (booktabs)."""

from __future__ import annotations

from .formatting import fmt_ci, fmt_delta, fmt_p


def _tex(s: str) -> str:
    return (s.replace("\\", "\\textbackslash{}").replace("_", "\\_").replace("%", "\\%").replace("&", "\\&")
            .replace("#", "\\#").replace("−", "$-$").replace("±", "$\\pm$").replace("Δ", "$\\Delta$")
            .replace("×", "$\\times$").replace("–", "--").replace("≥", "$\\geq$").replace("▲", "$\\blacktriangle$")
            .replace("▼", "$\\blacktriangledown$").replace("●", "$\\bullet$").replace("<", "$<$"))


def main_table(rows: list[dict], caption: str) -> str:
    """``rows``: dicts with backbone, method, rank1 (text), delta, ci_low, ci_high, p_holm, same, verdict, bold."""
    out = [
        "% Generated by SR4Rec. Requires \\usepackage{booktabs} and \\usepackage{amssymb}.",
        "\\begin{table}[t]",
        "\\centering",
        f"\\caption{{{_tex(caption)}}}",
        "\\begin{tabular}{llrrlrrl}",
        "\\toprule",
        "Backbone & SR & Rank-1 (\\%) & $\\Delta$ (pp) & 95\\% CI (pp) & $p$ (Holm) & Same sign & Verdict \\\\",
        "\\midrule",
    ]
    last = None
    for r in rows:
        if last is not None and r["backbone"] != last:
            out.append("\\midrule")
        last = r["backbone"]
        acc = _tex(r["rank1"])
        if r.get("bold"):
            acc = f"\\textbf{{{acc}}}"
        if r.get("delta") is None:
            cells = ["", "", "", "", ""]
        else:
            cells = [fmt_delta(r["delta"]), fmt_ci(r["ci_low"], r["ci_high"]), fmt_p(r["p_holm"]), r["same"], r["verdict"]]
        out.append(" & ".join([_tex(r["backbone"]), _tex(r["method"]), acc] + [_tex(c) for c in cells]) + " \\\\")
    out += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    return "\n".join(out)
