"""Build report.md, plots, table.tex and comparison panels from the results of a run.

Every sentence in the report is generated by fixed rules from the tables;
there is no free-text interpretation.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import TYPE_CHECKING

import numpy as np
import pandas as pd
from jinja2 import Environment, PackageLoader, StrictUndefined

from .. import __version__, stats
from ..data.sizes import MIN_IMAGES_PER_BIN, SIZE_BIN_LABELS, SIZE_BINS
from ..fingerprint import cpu_name
from ..utils import backbone_display
from . import comparisons as comp
from . import latex, plots
from .formatting import fmt_ci, fmt_delta, fmt_duration, fmt_int, fmt_mean_sd, fmt_num, fmt_p

if TYPE_CHECKING:  # pragma: no cover
    from ..pipeline import Run

HR = "hr"
BICUBIC = "bicubic"


def method_label(m: str) -> str:
    return {BICUBIC: "bicubic (baseline)", HR: "HR (upper bound)"}.get(m, m)


def _join(names: list[str]) -> str:
    if len(names) <= 1:
        return "".join(names)
    return ", ".join(names[:-1]) + " and " + names[-1]


def answer_text(stat: pd.DataFrame, sr_methods: list[str], n_backbones: int) -> str:
    if not sr_methods:
        return "No SR model was configured; only the bicubic baseline was evaluated."
    overall = stat[stat["size_bin"] == "all"]

    def counts(label: str) -> list[str]:
        out = []
        for m in sr_methods:
            k = int((overall[(overall["method"] == m)]["verdict"] == label).sum())
            if k:
                out.append(f"{m} ({k} of {n_backbones} backbone{'s' if n_backbones > 1 else ''})")
        return out

    gains, harms = counts(stats.GAIN), counts(stats.HARM)
    if not gains and not harms:
        return "No SR model changed Rank-1 accuracy significantly on any backbone."
    parts = []
    if gains:
        parts.append(f"{_join(gains)} improved Rank-1 accuracy significantly.")
    else:
        parts.append("No SR model improved Rank-1 accuracy significantly on any backbone.")
    if harms:
        parts.append(f"{_join(harms)} reduced Rank-1 accuracy significantly.")
    else:
        parts.append("No SR model reduced Rank-1 accuracy significantly.")
    return " ".join(parts)


def write_outputs(run: Run, run_dir: Path, pred: pd.DataFrame, metrics: pd.DataFrame, cmc_df: pd.DataFrame,
                  stat: pd.DataFrame, quality: pd.DataFrame, latency: list[dict], finished: str, total_seconds: float,
                  env: dict) -> tuple[Path, list[str]]:
    cfg = run.cfg
    backbones = list(cfg.recognizer.backbones)
    sr_methods = run.methods[1:]
    eval_methods = run.eval_methods
    seeds = list(cfg.recognizer.seeds)
    n_test = len(run.paths["test"])
    overall = metrics[metrics["size_bin"] == "all"]
    stat_all = stat[stat["size_bin"] == "all"]

    def per_seed(b: str, m: str, col: str) -> list[float]:
        return overall[(overall["backbone"] == b) & (overall["method"] == m)][col].astype(float).tolist()

    def mean_of(b: str, m: str, col: str) -> float:
        vals = per_seed(b, m, col)
        return float(np.mean(vals)) if vals else float("nan")

    # ---------------------------------------------------------------- plots
    plots_dir = run_dir / "plots"
    plots_dir.mkdir(exist_ok=True)
    plots.accuracy_by_size(metrics, eval_methods, backbones, plots_dir / "accuracy_by_size.png")
    plots.cmc_curves(cmc_df, eval_methods, backbones, plots_dir / "cmc.png")
    qual_mean = pd.DataFrame(columns=["method", "psnr", "ssim"])
    if run.synthetic and len(quality):
        qual_mean = quality.groupby("method", sort=False)[["psnr", "ssim"]].mean().reset_index()
        overall_mean = overall.groupby(["backbone", "method"], sort=False)["rank1"].mean().reset_index()
        plots.quality_vs_accuracy(qual_mean, overall_mean, run.methods, backbones,
                                  plots_dir / "quality_vs_accuracy.png")

    # ---------------------------------------------------------------- summary and main table
    summary_rows, main_rows, tex_rows, secondary_rows = [], [], [], []
    for b in backbones:
        bd = backbone_display(b)
        cands = [BICUBIC] + sr_methods
        best_acc = max(mean_of(b, m, "rank1") for m in cands)
        if sr_methods:
            best_sr = max(sr_methods, key=lambda m: mean_of(b, m, "rank1"))
            srow = stat_all[(stat_all["backbone"] == b) & (stat_all["method"] == best_sr)].iloc[0]
            summary_rows.append([bd, best_sr, fmt_delta(srow["delta"]), srow["verdict"]])
        for m in eval_methods:
            acc_txt = fmt_mean_sd(per_seed(b, m, "rank1"))
            bold = m != HR and abs(mean_of(b, m, "rank1") - best_acc) < 1e-12
            shown = f"**{acc_txt}**" if bold else acc_txt
            if m in sr_methods:
                r = stat_all[(stat_all["backbone"] == b) & (stat_all["method"] == m)].iloc[0]
                main_rows.append([bd, m, shown, fmt_delta(r["delta"]), fmt_ci(r["ci_low"], r["ci_high"]),
                                  fmt_p(r["p_holm"]), r["same_sign"], r["verdict"]])
                tex_rows.append({"backbone": bd, "method": m, "rank1": acc_txt, "bold": bold, "delta": r["delta"],
                                 "ci_low": r["ci_low"], "ci_high": r["ci_high"], "p_holm": r["p_holm"],
                                 "same": r["same_sign"], "verdict": r["verdict"]})
            else:
                main_rows.append([bd, method_label(m), shown, "", "", "", "", ""])
                tex_rows.append({"backbone": bd, "method": method_label(m), "rank1": acc_txt, "bold": bold,
                                 "delta": None})
        cols = ["rank1", "rank5", "precision", "recall", "f1"]
        best = {c: max((mean_of(b, m, c) for m in cands), default=float("nan")) for c in cols}
        for m in eval_methods:
            cells = []
            for c in cols:
                txt = fmt_mean_sd(per_seed(b, m, c))
                if m != HR and txt != "n/a" and abs(mean_of(b, m, c) - best[c]) < 1e-12:
                    txt = f"**{txt}**"
                cells.append(txt)
            secondary_rows.append([bd, method_label(m)] + cells)

    # ---------------------------------------------------------------- size bins
    test_bins = pd.Series([run.bin_of[p] for p in run.paths["test"]])
    bin_n = {sb: int((test_bins == sb).sum()) for sb in SIZE_BINS}
    bin_counts = ", ".join(f"{SIZE_BIN_LABELS[sb]}: {fmt_int(bin_n[sb])}" for sb in SIZE_BINS)
    size_rows = []
    for b in backbones:
        for m in sr_methods:
            cells = []
            for sb in SIZE_BINS:
                r = stat[(stat["backbone"] == b) & (stat["method"] == m) & (stat["size_bin"] == sb)]
                if not len(r):
                    cells.append("no images")
                    continue
                r = r.iloc[0]
                if r["verdict"] == stats.INSUFFICIENT:
                    cells.append(f"insufficient data ({int(r['n_images'])})")
                else:
                    cells.append(f"{r['verdict'].split(' ')[0]} {fmt_delta(r['delta'])}")
            size_rows.append([backbone_display(b), m] + cells)

    # ---------------------------------------------------------------- quality
    quality_rows, quality_summary = [], ""
    if run.synthetic and len(qual_mean):
        b0 = backbones[0]
        q = {r.method: r for r in qual_mean.itertuples()}
        best_psnr = max(q[m].psnr for m in run.methods)
        best_ssim = max(q[m].ssim for m in run.methods)
        best_acc0 = max(mean_of(b0, m, "rank1") for m in run.methods)
        best_f10 = max(mean_of(b0, m, "f1") for m in run.methods)

        def bold(txt: str, cond: bool) -> str:
            return f"**{txt}**" if cond else txt

        for m in run.methods:
            quality_rows.append([
                m,
                bold(fmt_num(q[m].psnr, 2), q[m].psnr == best_psnr),
                bold(fmt_num(q[m].ssim, 3), q[m].ssim == best_ssim),
                bold(fmt_num(100 * mean_of(b0, m, "rank1"), 1), mean_of(b0, m, "rank1") == best_acc0),
                bold(fmt_num(100 * mean_of(b0, m, "f1"), 1), mean_of(b0, m, "f1") == best_f10),
            ])
        top_psnr = max(run.methods, key=lambda m: q[m].psnr)
        top_ssim = max(run.methods, key=lambda m: q[m].ssim)
        top_acc = ", ".join(f"{max(run.methods, key=lambda m, b=b: mean_of(b, m, 'rank1'))} ({backbone_display(b)})"
                            for b in backbones)
        quality_summary = f"Highest PSNR: {top_psnr}. Highest SSIM: {top_ssim}. Highest accuracy: {top_acc}."

    # ---------------------------------------------------------------- latency
    lat = pd.DataFrame(latency, columns=["component", "sr", "backbone", "median_ms", "p95_ms"])

    def mp(r) -> str:
        return f"{r['median_ms']:.1f} / {r['p95_ms']:.1f}"

    latency_header = ["SR", "SR only"] + [f"Pipeline, {backbone_display(b)}" for b in backbones]
    latency_align = "l" + "r" * (len(latency_header) - 1)
    latency_rows = []
    for m in run.methods:
        src = run.sources[m]
        if not src.computes:
            latency_rows.append([m, "not measured"] + ["not measured"] * len(backbones))
            continue
        r = lat[(lat["component"] == "sr") & (lat["sr"] == m)]
        row = [m, mp(r.iloc[0]) if len(r) else "n/a"]
        for b in backbones:
            r = lat[(lat["component"] == "pipeline") & (lat["sr"] == m) & (lat["backbone"] == b)]
            row.append(mp(r.iloc[0]) if len(r) else "n/a")
        latency_rows.append(row)
    rec_lat = "; ".join(f"{backbone_display(r['backbone'])} {mp(r)}"
                        for _, r in lat[lat["component"] == "recognizer"].iterrows())

    # ---------------------------------------------------------------- comparisons
    comparison_images, comparisons_text = [], ""
    if cfg.comparisons.enabled:
        comparison_images, comparisons_text = export_comparisons(run, run_dir, pred, quality)

    # ---------------------------------------------------------------- setup
    mode_text = (f"`synthetic`: HR images downsampled ×{cfg.scale} (MATLAB-style bicubic)" if run.synthetic
                 else f"`native-lr`: images used as given (no downsampling); SR upscales ×{cfg.scale}")
    protocol_text = ("`matched`: train, val and test images all pass through the same SR model; one recognizer per "
                     "SR model, backbone and seed" if not run.fixed else
                     "`fixed_recognizer`: one recognizer per backbone and seed, trained on "
                     + ("HR images" if run.synthetic else "bicubic-upscaled images")
                     + "; only the test images pass through SR")
    tr = cfg.training
    setup_rows = [
        ["Dataset", f"`{cfg.dataset}` ({fmt_int(len(run.table))} images, {fmt_int(len(run.ds.classes))} classes)"],
        ["Mode", mode_text],
        ["Protocol", protocol_text],
        ["Split", run.split.description],
        ["Recognizer input", f"{cfg.recognizer.input_size} × {cfg.recognizer.input_size}: letterbox (aspect ratio "
                             "kept, ImageNet-mean padding), ImageNet normalization"],
        ["Backbones", ", ".join(backbone_display(b) for b in backbones)
         + ("" if cfg.recognizer.pretrained else " (not pretrained)")],
        ["Training", f"{tr.epochs} epochs, batch {tr.batch_size}, AdamW lr {tr.learning_rate:g}, weight decay "
                     f"{tr.weight_decay:g}, cosine schedule, best val Rank-1 checkpoint"],
        ["Seeds", ", ".join(str(s) for s in seeds)],
        ["Statistics", f"bootstrap CI and sign-flip permutation test over test images, "
                       f"{fmt_int(stats.N_RESAMPLES)} resamples each, Holm per backbone, alpha {stats.ALPHA}; "
                       f"size bins with fewer than {MIN_IMAGES_PER_BIN} test images are not tested"],
        ["Device", f"{env['gpu'] or env['cpu']}"],
    ]
    sr_rows = []
    for m in run.methods:
        s = run.sources[m]
        if m == BICUBIC:
            sr_rows.append(["bicubic (baseline)", f"×{s.scale}", "n/a", "built-in", "n/a", "n/a"])
            continue
        sha = next(iter(s.files.values()), "")
        source = {"weights": "weights (spandrel)", "module": "module", "images": "images"}[s.kind]
        sr_rows.append([m, f"×{s.scale}", s.trained_for, source, f"`{s.display_file}`", f"`{sha[:7]}…`" if sha else "n/a"])

    warnings = list(dict.fromkeys(run.warnings))
    for sb in SIZE_BINS:
        if 0 < bin_n[sb] < MIN_IMAGES_PER_BIN and sr_methods:
            warnings.append(f"{fmt_int(bin_n[sb])} test images fall in the {SIZE_BIN_LABELS[sb]} bin; no test is "
                            "reported for that bin.")
    if not warnings:
        warnings = ["None."]

    run_name = run_dir.name
    ctx = {
        "dataset_name": run.ds.name,
        "answer": answer_text(stat, sr_methods, len(backbones)),
        "run_row": [f"`{run_name}`", __version__, finished, fmt_duration(total_seconds)],
        "summary_rows": summary_rows,
        "setup_rows": setup_rows,
        "sr_rows": sr_rows,
        "n_seeds_text": f"{len(seeds)} seed{'s' if len(seeds) > 1 else ''}",
        "n_test": fmt_int(n_test),
        "main_rows": main_rows,
        "rank5_na": len(run.ds.classes) < 5,
        "secondary_rows": secondary_rows,
        "bin_counts": bin_counts,
        "bin_headers": [SIZE_BIN_LABELS[s] for s in SIZE_BINS],
        "size_rows": size_rows,
        "min_bin": MIN_IMAGES_PER_BIN,
        "synthetic": run.synthetic,
        "first_backbone": backbone_display(backbones[0]),
        "quality_rows": quality_rows,
        "quality_summary": quality_summary,
        "latency_enabled": cfg.latency.enabled,
        "lr_size": cfg.latency.lr_size,
        "threads": cfg.latency.threads,
        "cpu": cpu_name(),
        "latency_header": latency_header,
        "latency_align": latency_align,
        "latency_rows": latency_rows,
        "recognizer_latency": rec_lat or "n/a",
        "comparisons": cfg.comparisons.enabled,
        "comparisons_text": comparisons_text,
        "comparison_images": comparison_images[:2],
        "warnings": warnings,
        "rerun_path": _display_path(run_dir / "sr4rec.yaml"),
    }
    env_j = Environment(loader=PackageLoader("sr4rec", "templates"), undefined=StrictUndefined,
                        keep_trailing_newline=True, trim_blocks=False, lstrip_blocks=False)
    text = env_j.get_template("report.md.j2").render(**ctx)
    text = _tidy(text)
    report = run_dir / "report.md"
    report.write_text(text, encoding="utf-8")
    caption = (f"Rank-1 accuracy (%) on {run.ds.name}, mean ± sd over {len(seeds)} seed(s); Δ, 95% CI and p "
               "(Holm) versus bicubic.")
    (run_dir / "table.tex").write_text(latex.main_table(tex_rows, caption), encoding="utf-8")

    summary = [f"Done in {fmt_duration(total_seconds)}. Answer: {ctx['answer']}"]
    for r in summary_rows:
        summary.append(f"  {r[0]}: best SR {r[1]}, {r[2]} pp vs bicubic, {r[3]}")
    summary.append(f"Report: {report}")
    return report, summary


def _display_path(p: Path) -> str:
    """Path relative to the current folder (where the user ran SR4Rec), absolute if impossible."""
    try:
        return Path(os.path.relpath(p)).as_posix()
    except ValueError:
        return str(p)


def _tidy(text: str) -> str:
    """Collapse runs of blank lines (keeps the Markdown lint-clean)."""
    out, blank = [], 0
    for line in text.splitlines():
        if line.strip() == "":
            blank += 1
            if blank > 1:
                continue
        else:
            blank = 0
        out.append(line.rstrip())
    return "\n".join(out).strip() + "\n"


def export_comparisons(run: Run, run_dir: Path, pred: pd.DataFrame, quality: pd.DataFrame) -> tuple[list[str], str]:
    cfg = run.cfg
    backbone = cfg.comparisons.backbone or cfg.recognizer.backbones[0]
    seed = cfg.recognizer.seeds[0]
    test = run.paths["test"]
    sub = pred[(pred["backbone"] == backbone) & (pred["seed"] == seed)]
    table = {m: sub[sub["method"] == m].set_index("path") for m in run.eval_methods}
    correct = {m: table[m].loc[test, "correct"].to_numpy() for m in run.eval_methods}
    chosen = comp.select(test, correct[BICUBIC], [correct[m] for m in run.methods[1:]], cfg.comparisons.count,
                         cfg.comparisons.selection)
    qidx = quality.set_index(["method", "path"]) if len(quality) else None
    out_dir = run_dir / "comparisons"
    out_dir.mkdir(exist_ok=True)
    rows, files = [], []
    for i, (path, reason) in enumerate(chosen, 1):
        w, h = run.lr_dims[path]
        cells = [comp.Cell(f"LR input ({w} × {h} px)", run.lr_file(path))]
        for m in run.eval_methods:
            item = run.image_item(m, path)
            title = {BICUBIC: "Bicubic", HR: "HR (reference)"}.get(m, m)
            psnr = ssim = None
            if qidx is not None and m != HR:
                psnr, ssim = (float(v) for v in qidx.loc[(m, path), ["psnr", "ssim"]])
            cells.append(comp.Cell(title, item.file, pred=str(table[m].loc[path, "pred"]),
                                   correct=bool(table[m].loc[path, "correct"]), psnr=psnr, ssim=ssim,
                                   crop_scale=item.crop_scale))
        title = (f"{path} | true: {run.label_of[path]} | {backbone_display(backbone)}, seed {seed} | "
                 f"protocol: {cfg.protocol}")
        name = comp.file_name(i, path)
        comp.render(title, cells, run.synthetic, out_dir / name)
        rows.append({"file": name, "path": path, "label": run.label_of[path], "reason": reason})
        files.append(name)
    pd.DataFrame(rows, columns=["file", "path", "label", "reason"]).to_csv(out_dir / "index.csv", index=False)
    n = {r: sum(1 for x in rows if x["reason"] == r) for r in ("corrected", "degraded", "random")}
    if cfg.comparisons.selection == "mixed":
        text = (f"Before-SR and after-SR panels for {len(rows)} test images ({n['corrected']} corrected by at least "
                f"one SR model, {n['degraded']} degraded by at least one SR model, {n['random']} random; selection "
                f"seed {comp.SELECTION_SEED}; predictions of {backbone_display(backbone)}, seed {seed}).")
    elif cfg.comparisons.selection == "random":
        text = (f"Before-SR and after-SR panels for {len(rows)} randomly selected test images (selection seed "
                f"{comp.SELECTION_SEED}; predictions of {backbone_display(backbone)}, seed {seed}).")
    else:
        text = f"Before-SR and after-SR panels for all {len(rows)} test images."
    return files, text
